// Copyright 2024 The Bedrock-RTL Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= Bedrock-RTL

WARNING: UNDER CONSTRUCTION. Everything is broken.

High quality and composable base RTL libraries in Verilog

== Prerequisites

You need to have the following tools installed in your environment.

* Bazel (tested with 7.3.1)
* Verible (tested with v0.0-3798-ga602f072)
* pre-commit (tested with 3.8.0)

#TODO(mgottscho): Add more as we implement more things.#

== Pre-Commit Hooks

We use pre-commit hooks to enforce code quality. To install the hooks, run:

[source,shell]
----
pre-commit install
----

They should automatically run on every commit.
You can also run them manually via:

[source,shell]
----
pre-commit run
----

== Testing

`verilog_elab_test` and `verilog_lint_test` rules use placeholder tools by default, so those tests will always pass unless you point at real tools.
To do this, set the following Bazel action environment variables to point to executables via the `--action_env` flag (which you can set in your `.bazelrc` file for convenience):
* `BAZEL_VERILOG_ELAB_TEST_TOOL`
* `BAZEL_VERILOG_LINT_TEST_TOOL`

[source,shell]
----
bazel test //...
----

== Continuous Integration

Using GitHub Actions, which currently just runs Verible lint and format tests.
