// Copyright 2024 The Bedrock-RTL Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= Bedrock-RTL Flow Register (Forward Variant) Specification

== Overview

A dataflow pipeline register that behaves like a 1-entry FIFO.
It uses the AMBA-inspired ready-valid handshake protocol for synchronizing pipeline stages and stalling when encountering backpressure hazards.
The data progress from one stage to another when both the corresponding ready signal and valid signal are both 1 on the same cycle.
Otherwise, the stage is stalled.
Data ordering is strictly preserved by the design.

NOTE: This variant of the flow register only registers the output signals in the "forward" direction with respect to the dataflow, i.e., the valid and data paths are registered but the ready path is not.
This allows the backpressure latency to be 0 cycles.

== Parameters

[cols="1,1,1,3"]
|===
| Parameter | Type | Scope | Description

| `BitWidth`
| `int`
| module
| Must be at least 1
|===

== Interfaces

[cols="1,1,1,1,3"]
|===
| Interface | Port Direction | Port Type | Port Name | Description

| Clock
| `input`
| `logic`
| `clk`
|

| Reset
| `input`
| `logic`
| `rst`
| Synchronous active-high

| Push
| `output`
| `logic`
| `push_ready`
|

| Push
| `input`
| `logic`
| `push_valid`
|

| Push
| `input`
| `logic [BitWidth-1:0]`
| `push_data`
| Flow controlled using the ready/valid handshake protocol


| Pop
| `input`
| `logic`
| `pop_ready`
|

| Pop
| `output`
| `logic`
| `pop_valid`
|

| Pop
| `output`
| `logic [BitWidth-1:0]`
| `pop_data`
| Flow controlled using the ready/valid handshake protocol
|===

== Assumptions

The following assumptions are constraints on the input stimulus to the design.

* BitWidth integration check: BitWidth parameter must be set to at least 1.
* Push-side backpressure check: If `push_valid` is 1 and `push_ready` is 0, then on the following cycle `push_valid` must still be 1 and `push_data` must not have changed.
* `push_data` known check: If `push_valid` is 1, `push_data` should not be unknown (X).
* `pop_ready` eventual validity check: If `pop_valid` is 1, `pop_ready` must eventually be 1.

== Timing, Latency, and Throughput

All outputs are registered other than `push_ready`, which has a combinational dependency on `pop_ready`.

[cols="1,1,3"]
|===
| Latency Metric | Cycles | Description

| Cut-through
| 1
| Minimum delay from `push_valid` to `pop_valid`

| Backpressure
| 0
| Minimum delay from `pop_ready` to `push_ready`
|===

This module can sustain a peak throughput of one transaction per cycle on both the push and pop interfaces.
