# SPDX-License-Identifier: Apache-2.0

load("@rules_hdl//verilog:providers.bzl", "verilog_library")
load("//bazel:br_verilog.bzl", "br_verilog_sim_test_tools_suite")
load("//bazel:verilog.bzl", "verilog_elab_test", "verilog_sim_coverage_aggregate")

package(default_visibility = ["//visibility:private"])

verilog_library(
    name = "br_gate_tb",
    srcs = ["br_gate_tb.sv"],
    deps = [
        "//gate/rtl:br_gate_mock",
        "//misc/sim:br_test_driver",
    ],
)

verilog_elab_test(
    name = "br_gate_tb_elab_test",
    tool = "slang",
    deps = [":br_gate_tb"],
)

br_verilog_sim_test_tools_suite(
    name = "br_gate_sim_test_tools_suite",
    tools = [
        "vcs",
        "verilator",
    ],
    deps = [":br_gate_tb"],
)

verilog_sim_coverage_aggregate(
    name = "br_gate_verilator_coverage",
    coverage_reports = [
        ":br_gate_sim_test_tools_suite_verilator_coverage",
    ],
    visibility = ["//:__pkg__"],
)
