name: Run Bazel build and tests
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  bazel:
    runs-on: self-hosted
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Copy ci.bazelrc
      working-directory: ${{ github.workspace }}
      run: cp /home/gh-actions/bedrock-infra/ci.bazelrc ci.bazelrc
    # Run build before tests because the logging is not chronologically ordered
    # if a build step fails while unrelated tests are running.
    - name: Build
      run: bazel build //...
    # Run cheaper tests first.
    - name: Python tests
      run: bazel test //python/...
    - name: Stardoc tests
      run: bazel test //bazel/...
    - name: Elab tests
      # Suppress log output to protect sensitive EDA tool information.
      run: bazel test //... --test_tag_filters=elab --test_output=summary
    - name: Lint tests
      # Suppress log output to protect sensitive EDA tool information.
      run: bazel test //... --test_tag_filters=lint --test_output=summary
    - name: Sim tests (dsim only)
      # Suppress log output to protect sensitive EDA tool information.
      run: bazel test //... --test_tag_filters=dsim --test_output=summary
    # TODO: iverilog tests
    # TODO: VCS tests
    # TODO: VCF tests
    # TODO: JG tests
