name: Nightly Tests

# Run once a day at midnight Pacific Daylight Time.
# Note: GitHub Actions cron is in UTC.
on:
  schedule:
    - cron: '0 7 * * *'  # Daily at 07:00 UTC → 00:00 PDT
  workflow_dispatch:     # Allow manual triggering

jobs:
  # Run bazel build before bazel tests because the logging is not chronologically
  # ordered if a build step fails while unrelated tests are running.
  bazel-build:
    runs-on: self-hosted
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Copy ci.bazelrc
      working-directory: ${{ github.workspace }}
      run: cp /home/gh-actions/bedrock-infra/ci.bazelrc ci.bazelrc
    - name: Build
      run: bazel build --noshow_loading_progress //...

  bazel-test-jg:
    runs-on: self-hosted
    needs: bazel-build
    outputs:
      total_tests: ${{ steps.test.outputs.total_tests }}
      passing_tests: ${{ steps.test.outputs.passing_tests }}
      exit_code: ${{ steps.test.outputs.exit_code }}
    steps:
    - name: Verilog formal tests (using Cadence JasperGold)
      id: test
      # Use --test_output=summary to suppress log output, even on failure (proprietary EDA tool output may be sensitive).
      # TODO(mgottscho): test everything, not just arb, once this workflow has been pipe cleaned.
      run: |
        bazel test --noshow_loading_progress //arb/fpv/... --test_tag_filters=jg 2>&1 | tee .bazel-test-jg.log
        BAZEL_EXIT_CODE=${PIPESTATUS[0]}
        TOTAL_TESTS=$(grep -Po '(?<=out of )\d+(?= test)' .bazel-test-jg.log)
        PASSING_TESTS=$(grep -Po '\d+(?= test passes?\.| tests pass)' .bazel-test-jg.log)
        echo "total_tests=$TOTAL_TESTS" >> $GITHUB_OUTPUT
        echo "passing_tests=$PASSING_TESTS" >> $GITHUB_OUTPUT
        echo "exit_code=$BAZEL_EXIT_CODE" >> $GITHUB_OUTPUT
        exit $BAZEL_EXIT_CODE

  jg-badge:
    runs-on: ubuntu-latest
    needs: bazel-test-jg
    steps:
    - name: Create jg badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.MGOTTSCHO_GISTS_SECRET }}
        gistID: c66dc2ddc0e513ba06ce338620977b26
        filename: jg.json
        label: "jg (nightly)"
        message: ${{ needs.bazel-test-jg.outputs.passing_tests }} of ${{ needs.bazel-test-jg.outputs.total_tests }} passing
        color: ${{ needs.bazel-test-jg.outputs.exit_code == '0' && 'brightgreen' || 'red' }}
